# Generated by Django 3.1.5 on 2021-03-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('parent_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentTopic', to='lessonPlans.topic')),
            ],
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('aim', models.CharField(default='Aim:', max_length=200)),
                ('objectives', models.TextField(blank=True)),
                ('activity', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('assigned_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(to='lessonPlans.Topic')),
            ],
        ),
    ]
