# Generated by Django 3.1.5 on 2021-03-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonPlans', '0002_auto_20210317_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
    ]
